algoritmo "exemplo2"
var
   idade: inteiro
   nome: caractere
   sal: real
inicio

// Informações do primeiro funcionario
 escreva("Digite a sua idade: ")
 leia(idade)
 escreva("Digite seu nome: ")
 leia(nome)
 escreva("Entre com seu salário: ")
 leia(sal)
 escreval("Seu nome: ", nome)
 escreval("Sua idade: ", idade)
 escreval("Seu salário: ", sal)
// Informações do segundo funcionario
 escreva("Digite a sua idade: ")
 leia(idade)
 escreva("Digite seu nome: ")
 leia(nome)
 escreva("Entre com seu salário: ")
 leia(sal)
 escreval("Seu nome: ", nome)
 escreval("Sua idade: ", idade)
 escreval("Seu salário: ", sal)


fimalgoritmo
